include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-divonet-files
PKG_VERSION:=1
PKG_RELEASE:=1

include $(TOPDIR)/../package/gluon.mk

define Package/gluon-divonet-files
  TITLE:=Different configfiles for DiVoNet
endef

$(eval $(call BuildPackageGluon,gluon-divonet-files))
