#!/bin/sh

uci set firewall.mesh.input='ACCEPT'
uci commit firewall
/etc/init.d/firewall reload

#Die Supernodes fest eintragen, da bei Wireguard DNS erst läuft, wenn die Verbindung steht.

#Erstmal alle alten Eintraege loeschen in der /etc/hosts
grep -vwE "(ffkwsn01|ffkwsn02|ffkwsn03)" /etc/hosts > /tmp/hosts.sik
mv /tmp/hosts.sik /etc/hosts
echo "195.8.226.26    ffkwsn01.freifunk-koenigswinter.de" >> /etc/hosts
echo "85.13.139.108   ffkwsn02.freifunk-koenigswinter.de" >> /etc/hosts
echo "144.91.101.189  ffkwsn03.freifunk-koenigswinter.de" >> /etc/hosts

 /etc/init.d/gluon-radvd disable
 /etc/init.d/gluon-radvd stop


