#!/bin/sh

uci set firewall.mesh.input='ACCEPT'
uci commit firewall

# delete old ffkwsn entries in /etc/hosts files
grep -vwE "(ffkwsn)" /etc/hosts > /tmp/hosts.sik
mv /tmp/hosts.sik /etc/hosts

/etc/init.d/gluon-radvd disable
/etc/init.d/gluon-radvd stop
